#
# Copyright (c) 2005-2009 rPath, Inc.
#
# All rights reserved
#

SUBDIRS =

python_files = __init__.py next_steps.py

all: default-all

install: raaplugins-install default-install

clean: default-clean


include ../../../../Make.rules
