#
# Copyright (c) 2005-2007 rPath, Inc.
#
# All Rights Reserved
#

SUBDIRS = templates content hooks

python_files = $(wildcard *.py)

all: default-all

install: pyfiles-install default-install

clean: default-clean


include ../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
