#
# Copyright (c) 2005-2007 rPath, Inc.
#
# All Rights Reserved
#

SUBDIRS = templates content

python_files = \
	__init__.py	\
	admin.py	\
	app.py		\
	cache.py	\
	fields.py	\
	repos.py	\
	rpchooks.py	\
	decorators.py	\
	hooks.py	\
	project.py	\
	setup.py	\
	site.py		\
	webhandler.py	\
	templatesupport.py \
	basictroves.py	\
	vmtn.py

all: default-all

install: pyfiles-install default-install

clean: default-clean


include ../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
