#
# Copyright (c) 2008 rPath, Inc.
#
# All rights reserved
#


kid_files = index.kid

python_files = __init__.py


all: kid-build default-all

install: raaplugins-install default-install

clean: kid-clean default-clean

include ../../../../Make.rules
