#
# Copyright (c) 2005-2007 rPath, Inc.
#
# All Rights Reserved
#

kid_files =			\
        feedback.kid            \
        overview.kid            \
        privacy.kid             \
        tos.kid                 \
	legal.kid

all: kid-build default-all

install: kid-install default-install

clean: kid-clean default-clean


include ../../../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
