#
# Copyright (c) 2004-2005 rPath, Inc.
#
# All Rights Reserved
#

python_files = __init__.py new_projects.py new_users.py mint_reports.py site_summary.py active_users.py exec_summary.py

extra_dist = Makefile

dist_files = $(python_files) $(extra_dist)

all: default-all

install: install-subdirs pyfiles-install

dist: default-dist

clean: default-clean

include ../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
