#
# Copyright (c) 2004-2005 rPath, Inc.
#
# All Rights Reserved
#

python_files =		\
	__init__.py	\
	commands.py	\
	releases.py	\
	users.py

extra_dist = Makefile

dist_files = $(python_files) $(extra_dist)

all: default-all

install: install-subdirs pyfiles-install

dist: default-dist

clean: default-clean

include ../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
