#!/bin/sh
#
# Copyright (c) SAS Institute Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if ! which pylint > /dev/null 2>&1; then
   echo "pylint is not installed"
   exit 0
fi

if [ -x reports ]; then
   rm -rf reports;
fi
mkdir reports
cd reports

if [ -z "$*" ]; then
    files="mint"
else
    files=$@
fi

PYTHONPATH=`pwd`/.. pylint --init-hook='import os, sys; sys.path.append(os.path.realpath("..")); import init_pylint' --rcfile='../pylintrc' $files
rc=$?
for file in `ls`; do
   if [ ! -s $file ]; then
      rm $file;
   fi
done
exit $rc
