#
# Copyright (c) 2008-2009 rPath, Inc.
#
# All rights reserved
#

SUBDIRS = web srv

python_files = __init__.py lib.py

kid_files = index.kid firstTimeSetup.kid


all: kid-build default-all

install: raaplugins-install default-install

clean: kid-clean default-clean


include ../../../Make.rules
