#
# Copyright (c) 2005-2007 rPath, Inc.
#
# All Rights Reserved
#

SUBDIRS = css javascript images

override STATICDEST = /usr/share/conary/web-common/apps/mint

all: default-all

install: default-install

clean: default-clean


include ../../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
