#
# Copyright (c) 2011 rPath, Inc.
#
# All rights reserved.
#

SUBDIRS = docs discovery favorites images inventory jobs manager metrics modellib notices packageindex packages platforms products projects querysets rbac reporting repos session targets users

python_files = $(wildcard *.py)

all: default-all

install: pyfiles-install default-install

clean: default-clean


include ../../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
