#
# Copyright (c) rPath, Inc.
#

SUBDIRS = docs discovery favorites images inventory jobs manager metrics modellib modulehooks packageindex platforms products projects querysets rbac repos session targets users xmlresources

python_files = $(wildcard *.py)

all: default-all

install: pyfiles-install default-install

clean: default-clean


include ../../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
