#
# Copyright (c) 2011 rPath, Inc.
#
# All rights reserved.
#

SUBDIRS = docs discovery platforms reporting inventory metrics modellib manager querysets packages changelog projects jobs packageindex notices targets users modulehooks rbac repos images

python_files = $(wildcard *.py)

all: default-all

install: pyfiles-install default-install

clean: default-clean


include ../../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
