#!/bin/bash -e

if [ ! -f "$MINT_DIST_PATH" ] ; then
    echo "WARNING: Using hg mint at $MINT_PATH"
    echo "To test for release, please run MINT_DIST_PATH=/path/to/tarball $0"
else
    echo "Testing release candidate tarball $MINT_DIST_PATH"
    TESTDIR=$(mktemp -d /tmp/mint-dist-XXXXXX) || { echo failure; exit 1; }
    tar -x -j -C $TESTDIR -f $MINT_DIST_PATH
    export MINT_SRC=$(echo $TESTDIR/*)
    make -s -C $MINT_SRC
    make -s -C $MINT_SRC DESTDIR=$TESTDIR/_ROOT_/ install
    export MINT_PATH=$TESTDIR/_ROOT_/usr/lib/python2.4/site-packages//
fi

numtests=4
curtest=1
desc="sqlite backend"

echo "$curtest/$numtests - $desc"
MINT_SQL=sqlite ./testsuite.py "$@"

desc="mysql backend"
curtest=$(expr $curtest + 1)
echo "$curtest/$numtests - $desc"
MINT_SQL=mysql ./testsuite.py "$@"

desc="sqlite backend: no ssl"
curtest=$(expr $curtest + 1)
echo "$curtest/$numtests - $desc"
MINT_SQL=sqlite MINT_TEST_NOSSL=1 ./testsuite.py "$@"

desc="mysql backend: no ssl"
curtest=$(expr $curtest + 1)
echo "$curtest/$numtests - $desc"
MINT_SQL=mysql MINT_TEST_NOSSL=1 ./testsuite.py "$@"

[ -d "$TESTDIR" -a "$TESTDIR" != / ] && rm -rf "$TESTDIR"
