#
# Copyright (c) 2008-2009 rPath, Inc.
#
# All rights reserved
#

SUBDIRS = static

python_files = 	\
		__init__.py \
		rbasetup.py

all: default-all

install: raaplugins-install default-install

clean: default-clean


include ../../../../Make.rules
