#
# Copyright (c) 2009 rPath, Inc.
#
# All Rights Reserved
#

python_files =		\
	__init__.py

doc_files =		\
	rmakemanagement.xml


all: doc-build default-all

install: doc-install raaplugins-install default-install

clean: doc-clean default-clean


include ../../../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
