#!/usr/bin/python
#
# Copyright (c) 2006 rPath, Inc.
#

import sys
import os
from mint.nagpy.checkjs import CheckJS

obj = CheckJS()
d = obj.check()
if d:
    print 'Jobserver(s) malfunctioning on host %s' % os.uname()[1]
else:
    print 'Jobserver(s) running on host %s' % os.uname()[1]
sys.exit(d)
