#!/usr/bin/python
#
# Copyright (c) 2006 rPath, Inc.
#

import sys
from mint.nagpy.checkjsrb import CheckJSRB
from nagpy import plugin
from mint import jobstatus

obj = CheckJSRB()
jobs = obj.check()
    
if len(jobs):
	print 'Problems detected with the following jobs: %s' % str(jobs)
else:
	print 'No errant jobs detected'
sys.exit(len(jobs) and plugin.NagiosPlugin.nagios_critical or plugin.NagiosPlugin.nagios_ok)
