#
# Copyright (c) 2005 rPath, Inc.
#
# All Rights Reserved
#

SUBDIRS = 

python_files =				\
		checkjobs.py		\
		checkjobserver.py	\
		checkjs.py		\
		checkjsrb.py		\
		check_jobs		\
		__init__.py		\
		config.py		\
		check_jobserver

extra_dist = Makefile

dist_files = $(python_files) $(extra_dist)

all: 

install:

dist: default-dist

clean:

include ../Make.rules

# vim: set sts=8 sw=8 noexpandtab :
