#
# Copyright (c) 2005-2007 rPath, Inc.
#
# All rights reserved
#

SUBDIRS = inboundmirror outboundmirror loadmirror mcpconsole repoconvert rmakemanagement

extra_dist = __init__.py

all: default-all

install: default-install

clean: default-clean


include ../../Make.rules
