#
# Copyright (c) 2005 rpath, Inc.
#
# All Rights Reserved
#

SUBDIRS = pixmaps

dist_files = Makefile

all: default-subdirs

install: install-subdirs

subdirs: default-subdirs

dist: default-dist dist-subdirs

clean: default-clean clean-subdirs

include ../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
