#
# Copyright (c) 2009 rPath, Inc.
#
# All Rights Reserved
#

static_files =			\
	wait.gif		\
	check.gif


all: default-all

install: static-install default-install

clean: default-clean


include ../../../../../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
