.\" Copyright (c) 2006 rPath, Inc.
.TH RBUILDER 1 "08 Aug 2006" "rPath, Inc."
.SH NAME
rbuilder \- Command-line interface to rBuilder
.SH SYNOPSIS
.B rbuilder \fIcommand \fR[\fI<args>\fR]
.SH DESCRIPTION
\fBrbuilder\fR is the command-line interface to rBuilder.  Use of
\fBrbuilder\fR makes it possible to automate various aspects of rBuilder's
operation.

.SH REFERENCE
\fBrbuilder\fR includes commands to create a build, wait for a given build
to complete, display the URLs associated with a given build, create a new
rBuilder user, add a user to a project, and display rBuilder's
configuration.

\fBNOTE:\fR Before using \fBrbuilder\fR you must configure it.  See the
\fIFILES\fR section for configuration information.

.SS COMMANDS

.TP 4
.B build-create \fI<project-name>\fR \fI<trove-spec>\fR \fI<image-type>\fR [\fB--wait\fR]

Creates a build based on the following information:

\fI<project-name>\fR -- the desired project's hostname

 \fI<trove-spec>\fR -- a group trove specification in the format returned
by the command \fBconary rq --full-versions --flavors \fI<trove>\fR\fB

 \fI<image-type>\fR -- one of the following:

\fBinstallable_iso\fR, \fBraw_hd_image\fR, \fBraw_fs_image\fR,
\fBtarball\fR, \fBlive_iso\fR, \fBvmware_image\fR

Returns a build ID in a form suitable for use with \fBeval\fR.  Using the
\fB--wait\fR option causes \fBbuild-create\fR to block until the build
completes.

.TP 4
.B build-wait \fI<build-id>\fR

Blocks until build \fI<build-id>\fR has finished building.

.TP 4
.B build-url \fI<build-id>\fR

Lists the URLs of each file created by build \fI<build-id>\fR.

.TP 4
.B user-create \fI<username>\fR \fI<email>\fR [\fB--password\fR \fI<password>\fR]

Creates a new rBuilder user.

.TP 4
.B project-add \fI<username>\\fR \fI<project-name>\fR <\fBowner\fR|\fBdeveloper\fR>

Adds a user to an existing rBuilder project, giving them either \fBowner\fR
or \fBdeveloper\fR status.

.TP 4
.B config

Dumps the currently-used \fBrbuilder\fR configuration settings.

.SS OPTIONS

.TP 4
.B --version

Displays \fBrbuilder\fR's version number.

.TP 4
.B -h, --help

Displays usage information.

.SS COMMON OPTIONS

.TP 4
.B --config=\fI<key>\fR \fI<value>\fR

Sets the configuration setting \fI<key>\fR to \fI<value>\fR.

.TP 4
.B --config-file=\fI<path>\fR

Reads the configuration file \fI<path>\fR.

.TP 4
.B --debug

Prints debugging information (currently unimplemented).

.TP 4
.B --skip-default-config

Do not read the default configuration file (~/.rbuilderrc)

.SH FILES
.\" do not put excess space in the file list
.PD 0
.TP 4
\fI$HOME/.rbuilderrc
The configuration file for \fBrbuilder\fR.  This file must contain a
\fBserverUrl\fR line in the following form:

serverUrl http://\fI<username>\fR:\fI<password>\fR@\fI<rbuilder>\fR/xmlrpc-private/

Where:

\fI<username>\fR is the username with project developer or owner access to
the desired project

\fI<password>\fR is the password of the project developer/owner

\fI<rbuilder>\fR is the fully-qualified domain name of the rBuilder
instance

.SH BUGS
Please report bugs via http://issues.rpath.com/
.\"
.\"
.\"
.SH "SEE ALSO"
http://www.rpath.com/
.br
http://wiki.rpath.com/
