#
# Copyright (c) 2011 rPath, Inc.
#
# All rights reserved.
#

# These fixtures files aren't py files, but they get installed the same way.
python_files = $(wildcard *.xml)

all: default-all

install: pyfiles-install default-install

clean: default-clean


include ../../../../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
