#
# Copyright (c) 2005-2006 rPath, Inc.
#
# All Rights Reserved
#

import sys

validImageTypes = {
    'BOOTABLE_IMAGE'   : 0,
    'INSTALLABLE_ISO'  : 1,
    'STUB_IMAGE'       : 2,
    'RAW_FS_IMAGE'    : 3,
    'NETBOOT_IMAGE'    : 4,
    'GROUP_TROVE_COOK' : 5,
    'LIVE_ISO'         : 6,
    'RAW_HD_IMAGE'     : 7,
    'VMWARE_IMAGE'     : 8,
    }

TYPES = validImageTypes.values()

# add all the defined image types directly to the module so that the standard
# approach of "releasetypes.IMAGE_TYPE" will result in the expected enum
sys.modules[__name__].__dict__.update(validImageTypes)

deprecatedImageTypes = {
    'QEMU_IMAGE' : RAW_HD_IMAGE
    }


#BOOTABLE_IMAGE Should never get stored in the DB and therefore doesn't need a name
typeNames = {
    NETBOOT_IMAGE:      "Netboot Image",
    INSTALLABLE_ISO:    "Installable CD/DVD",
    RAW_FS_IMAGE:       "Raw Filesystem Image",
    STUB_IMAGE:         "Stub Image (for testing)",
    RAW_HD_IMAGE:       "Raw Hard Disk Image",
    VMWARE_IMAGE:       "VMware Player Image",
    LIVE_ISO:           "Live CD/DVD",
}

typeNamesShort = {
    NETBOOT_IMAGE:      "Netboot",
    INSTALLABLE_ISO:    "Inst CD/DVD",
    RAW_FS_IMAGE:       "Raw FS",
    STUB_IMAGE:         "Stub",
    RAW_HD_IMAGE:       "HDD",
    VMWARE_IMAGE:       "VMware",
    LIVE_ISO:           "Live CD/DVD",
}


# sizes are listed in bytes...
discSizes = {
    'CD: 650 MB'  : '681574400',
    'CD: 700 MB'  : '734003200',
    'DVD: 4.7 GB' : '4700000000',
    'DVD: 8.5 GB' : '8500000000',
    }

def getImageName(nameIndex, size = 0, short = False):
    if short:
        baseName = typeNamesShort[nameIndex]
    else:
        baseName = typeNames[nameIndex]
    if 'CD/DVD' not in baseName:
        return baseName

    try:
        app = sorted([(int(x[1]),x[0]) for x in discSizes.iteritems() \
                      if size <= int(x[1])])[0][1]
    except IndexError:
        # index error means your disc was too big
        app = 'DVD: Overburn'
    if short:
        app = app.split(':')[0]
    return baseName.replace('CD/DVD', app)

# code generator run by make to generate javascript constants
# should only be run by the makefile in mint/web/content/javascript
if __name__ == "__main__":
    if sys.argv[1] == "--genjs":
        print "// this Javascript was generated by mint/releasestypes.py"
        print "// do not edit or check into source control"

        print "var releaseImageTypeNames = { "
        i = []
        for k, v in typeNames.items():
            i.append("    '%d':  '%s'" % (k, v,))
        print ",\n".join(i)
        print "};"

        print "var releaseImageTypeNamesShort = { "
        i = []
        for k, v in typeNamesShort.items():
            i.append("    '%d':  '%s'" % (k, v,))
        print ",\n".join(i)
        print "};"

        sys.exit(0)
    else:
        sys.exit(1)


