#
# Copyright (c) 2005-2007 rPath, Inc.
#
# All Rights Reserved
#

kid_files =			\
	add_outbound.kid	\
	addExternal.kid		\
	frontPage.kid		\
	external.kid		\
	maintenance.kid		\
	mirrortarget.kid	\
	report.kid		\
	outbound.kid		\
	newUser.kid		\
	jobs.kid		\
	admin.kid	\
	spotlight.kid		\
	preview.kid	\
	selections.kid		\
	useit.kid

all: kid-build default-all

install: kid-install default-install

clean: kid-clean default-clean


include ../../../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
