#
# Copyright (c) 2005-2007 rPath, Inc.
#
# All Rights Reserved
#

kid_files = \
	joinRequest.kid		\
	registerNewUser.kid	\
	validateNewEmail.kid

python_files = __init__.py

all: kid-build default-all

install: all kid-install pyfiles-install default-install

clean: kid-clean default-clean


include ../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
