#
# Copyright (c) 2010 rPath, Inc.
#
# All rights reserved.
#

static_files = $(wildcard *.py)

override STATICDEST = /usr/lib64/rmake3


all: default-all

install: static-install default-install

clean: default-clean


include ../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
