#
# Copyright (c) 2005-2007 rPath, Inc.
#
# All rights reserved
#

static_files = mirror_now.png

all: default-all

install: static-install default-install

clean: default-clean


include ../../../../../../Make.rules
