#
# Copyright (c) 2011 rPath, Inc.
#

SUBDIRS = upload wig

python_files = $(wildcard *.py)


all: default-all

install: pyfiles-install default-install

clean: default-clean


include ../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
