#
# Copyright (c) 2004-2005 rpath, Inc.
#
# All Rights Reserved
#

conf_dist = *.conf *.include

extra_dist = Makefile

SUBDIRS =

dist_files = $(conf_dist) $(extra_dist)

all: default-all

dist: default-dist

clean: default-clean

install: default-install

include ../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
