#
# Copyright (c) 2007 rPath, Inc.
#
# All Rights Reserved
#

SUBDIRS = images javascript


all: default-all

install: default-install

clean: default-clean


include ../../../../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
