#
# Copyright (c) 2005-2007 rPath, Inc.
#
# All Rights Reserved
#

kid_files =			\
        add_group.kid           \
	browse.kid		\
	error.kid		\
	files.kid		\
	group_contents.kid	\
	lic_crypto_report.kid		\
	notice.kid		\
        permission.kid          \
	pgp_admin.kid		\
	shadow_diff.kid		\
	trove_info.kid          \
        user_admin.kid

python_files = __init__.py

all: kid-build default-all

install: kid-install pyfiles-install default-install

clean: kid-clean default-clean


include ../../../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
