#
# Copyright (c) 2011 rPath, Inc.
#

SUBDIRS = plugins

override PYDEST = twisted

all: default-all

install: default-install

clean: default-clean


include ../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
