#
# Copyright (c) 2005 rpath, Inc.
#
# All Rights Reserved
#

SUBDIRS = content templates

dist_files =

all: default-subdirs

install: install-subdirs

subdirs: default-subdirs

dist: default-dist dist-subdirs

clean: default-clean clean-subdirs

include ../Make.rules
