#!/usr/bin/env python

#
# Generated  by generateDS.py.
#

import sys
import getopt
from string import lower as str_lower
from xml.dom import minidom
from xml.dom import Node

#
# User methods
#
# Calls to the methods in these classes are generated by generateDS.py.
# You can replace these methods by re-implementing the following class
#   in a module named generatedssuper.py.

try:
    from generatedssuper import GeneratedsSuper
except ImportError, exp:

    class GeneratedsSuper(object):
        def format_string(self, input_data, input_name=''):
            return input_data
        def format_integer(self, input_data, input_name=''):
            return '%d' % input_data
        def format_float(self, input_data, input_name=''):
            return '%f' % input_data
        def format_double(self, input_data, input_name=''):
            return '%e' % input_data
        def format_boolean(self, input_data, input_name=''):
            return '%s' % input_data


#
# If you have installed IPython you can uncomment and use the following.
# IPython is available from http://ipython.scipy.org/.
#

## from IPython.Shell import IPShellEmbed
## args = ''
## ipshell = IPShellEmbed(args,
##     banner = 'Dropping into IPython',
##     exit_msg = 'Leaving Interpreter, back to program.')

# Then use the following line where and when you want to drop into the
# IPython shell:
#    ipshell('<some message> -- Entering ipshell.\nHit Ctrl-D to exit')

#
# Globals
#

ExternalEncoding = 'utf-8'

#
# Support/utility functions.
#

def showIndent(outfile, level):
    for idx in range(level):
        outfile.write('    ')

def quote_xml(inStr):
    s1 = (isinstance(inStr, basestring) and inStr or
          '%s' % inStr)
    s1 = s1.replace('&', '&amp;')
    s1 = s1.replace('<', '&lt;')
    s1 = s1.replace('>', '&gt;')
    return s1

def quote_attrib(inStr):
    s1 = (isinstance(inStr, basestring) and inStr or
          '%s' % inStr)
    s1 = s1.replace('&', '&amp;')
    s1 = s1.replace('<', '&lt;')
    s1 = s1.replace('>', '&gt;')
    if '"' in s1:
        if "'" in s1:
            s1 = '"%s"' % s1.replace('"', "&quot;")
        else:
            s1 = "'%s'" % s1
    else:
        s1 = '"%s"' % s1
    return s1

def quote_python(inStr):
    s1 = inStr
    if s1.find("'") == -1:
        if s1.find('\n') == -1:
            return "'%s'" % s1
        else:
            return "'''%s'''" % s1
    else:
        if s1.find('"') != -1:
            s1 = s1.replace('"', '\\"')
        if s1.find('\n') == -1:
            return '"%s"' % s1
        else:
            return '"""%s"""' % s1


class MixedContainer:
    # Constants for category:
    CategoryNone = 0
    CategoryText = 1
    CategorySimple = 2
    CategoryComplex = 3
    # Constants for content_type:
    TypeNone = 0
    TypeText = 1
    TypeString = 2
    TypeInteger = 3
    TypeFloat = 4
    TypeDecimal = 5
    TypeDouble = 6
    TypeBoolean = 7
    def __init__(self, category, content_type, name, value):
        self.category = category
        self.content_type = content_type
        self.name = name
        self.value = value
    def getCategory(self):
        return self.category
    def getContenttype(self, content_type):
        return self.content_type
    def getValue(self):
        return self.value
    def getName(self):
        return self.name
    def export(self, outfile, level, name, namespace):
        if self.category == MixedContainer.CategoryText:
            outfile.write(self.value)
        elif self.category == MixedContainer.CategorySimple:
            self.exportSimple(outfile, level, name)
        else:    # category == MixedContainer.CategoryComplex
            self.value.export(outfile, level, namespace,name)
    def exportSimple(self, outfile, level, name):
        if self.content_type == MixedContainer.TypeString:
            outfile.write('<%s>%s</%s>' % (self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeInteger or \
                self.content_type == MixedContainer.TypeBoolean:
            outfile.write('<%s>%d</%s>' % (self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeFloat or \
                self.content_type == MixedContainer.TypeDecimal:
            outfile.write('<%s>%f</%s>' % (self.name, self.value, self.name))
        elif self.content_type == MixedContainer.TypeDouble:
            outfile.write('<%s>%g</%s>' % (self.name, self.value, self.name))
    def exportLiteral(self, outfile, level, name):
        if self.category == MixedContainer.CategoryText:
            showIndent(outfile, level)
            outfile.write('model_.MixedContainer(%d, %d, "%s", "%s"),\n' % \
                (self.category, self.content_type, self.name, self.value))
        elif self.category == MixedContainer.CategorySimple:
            showIndent(outfile, level)
            outfile.write('model_.MixedContainer(%d, %d, "%s", "%s"),\n' % \
                (self.category, self.content_type, self.name, self.value))
        else:    # category == MixedContainer.CategoryComplex
            showIndent(outfile, level)
            outfile.write('model_.MixedContainer(%d, %d, "%s",\n' % \
                (self.category, self.content_type, self.name,))
            self.value.exportLiteral(outfile, level + 1)
            showIndent(outfile, level)
            outfile.write(')\n')


class MemberSpec_(object):
    def __init__(self, name='', data_type='', container=0):
        self.name = name
        self.data_type = data_type
        self.container = container
    def set_name(self, name): self.name = name
    def get_name(self): return self.name
    def set_data_type(self, data_type): self.data_type = data_type
    def get_data_type_chain(self): return self.data_type
    def get_data_type(self):
        if isinstance(self.data_type, list):
            if len(self.data_type) > 0:
                return self.data_type[-1]
            else:
                return 'xs:string'
        else:
            return self.data_type
    def set_container(self, container): self.container = container
    def get_container(self): return self.container

def _cast(typ, value):
    if typ is None or value is None:
        return value
    return typ(value)

#
# Data representation classes.
#

class managedSystemType(GeneratedsSuper):
    member_data_items_ = [
        MemberSpec_('generatedUUID', ['string64', 'xsd:token'], 0),
        MemberSpec_('localUUID', ['string64', 'xsd:token'], 0),
        MemberSpec_('registrationDate', 'xsd:string', 0),
        MemberSpec_('sslClientCertificate', ['string8092', 'xsd:token'], 0),
        MemberSpec_('sslClientKey', ['string8092', 'xsd:token'], 0),
        MemberSpec_('sslServerCertificate', ['string8092', 'xsd:token'], 0),
        ]
    subclass = None
    superclass = None
    def __init__(self, generatedUUID=None, localUUID=None, registrationDate=None, sslClientCertificate=None, sslClientKey=None, sslServerCertificate=None):
        self.generatedUUID = generatedUUID
        self.localUUID = localUUID
        self.registrationDate = registrationDate
        self.sslClientCertificate = sslClientCertificate
        self.sslClientKey = sslClientKey
        self.sslServerCertificate = sslServerCertificate
    def factory(*args_, **kwargs_):
        if managedSystemType.subclass:
            return managedSystemType.subclass(*args_, **kwargs_)
        else:
            return managedSystemType(*args_, **kwargs_)
    factory = staticmethod(factory)
    def get_generatedUUID(self): return self.generatedUUID
    def set_generatedUUID(self, generatedUUID): self.generatedUUID = generatedUUID
    def validate_generatedUUID(self, value):
        # validate type generatedUUID
        pass
    def get_localUUID(self): return self.localUUID
    def set_localUUID(self, localUUID): self.localUUID = localUUID
    def validate_localUUID(self, value):
        # validate type localUUID
        pass
    def get_registrationDate(self): return self.registrationDate
    def set_registrationDate(self, registrationDate): self.registrationDate = registrationDate
    def get_sslClientCertificate(self): return self.sslClientCertificate
    def set_sslClientCertificate(self, sslClientCertificate): self.sslClientCertificate = sslClientCertificate
    def validate_sslClientCertificate(self, value):
        # validate type sslClientCertificate
        pass
    def get_sslClientKey(self): return self.sslClientKey
    def set_sslClientKey(self, sslClientKey): self.sslClientKey = sslClientKey
    def validate_sslClientKey(self, value):
        # validate type sslClientKey
        pass
    def get_sslServerCertificate(self): return self.sslServerCertificate
    def set_sslServerCertificate(self, sslServerCertificate): self.sslServerCertificate = sslServerCertificate
    def validate_sslServerCertificate(self, value):
        # validate type sslServerCertificate
        pass
    def export(self, outfile, level, namespace_='inv:', name_='managedSystemType', namespacedef_=''):
        showIndent(outfile, level)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        self.exportAttributes(outfile, level, namespace_, name_='managedSystemType')
        if self.hasContent_():
            outfile.write('>\n')
            self.exportChildren(outfile, level + 1, namespace_, name_)
            showIndent(outfile, level)
            outfile.write('</%s%s>\n' % (namespace_, name_))
        else:
            outfile.write('/>\n')
    def exportAttributes(self, outfile, level, namespace_='inv:', name_='managedSystemType'):
        pass
    def exportChildren(self, outfile, level, namespace_='inv:', name_='managedSystemType'):
        if self.generatedUUID is not None:
            showIndent(outfile, level)
            outfile.write('<%sgeneratedUUID>%s</%sgeneratedUUID>\n' % (namespace_, self.format_string(quote_xml(self.generatedUUID).encode(ExternalEncoding), input_name='generatedUUID'), namespace_))
        if self.localUUID is not None:
            showIndent(outfile, level)
            outfile.write('<%slocalUUID>%s</%slocalUUID>\n' % (namespace_, self.format_string(quote_xml(self.localUUID).encode(ExternalEncoding), input_name='localUUID'), namespace_))
        if self.registrationDate is not None:
            showIndent(outfile, level)
            outfile.write('<%sregistrationDate>%s</%sregistrationDate>\n' % (namespace_, self.format_string(quote_xml(self.registrationDate).encode(ExternalEncoding), input_name='registrationDate'), namespace_))
        if self.sslClientCertificate is not None:
            showIndent(outfile, level)
            outfile.write('<%ssslClientCertificate>%s</%ssslClientCertificate>\n' % (namespace_, self.format_string(quote_xml(self.sslClientCertificate).encode(ExternalEncoding), input_name='sslClientCertificate'), namespace_))
        if self.sslClientKey is not None:
            showIndent(outfile, level)
            outfile.write('<%ssslClientKey>%s</%ssslClientKey>\n' % (namespace_, self.format_string(quote_xml(self.sslClientKey).encode(ExternalEncoding), input_name='sslClientKey'), namespace_))
        if self.sslServerCertificate is not None:
            showIndent(outfile, level)
            outfile.write('<%ssslServerCertificate>%s</%ssslServerCertificate>\n' % (namespace_, self.format_string(quote_xml(self.sslServerCertificate).encode(ExternalEncoding), input_name='sslServerCertificate'), namespace_))
    def hasContent_(self):
        if (
            self.generatedUUID is not None or
            self.localUUID is not None or
            self.registrationDate is not None or
            self.sslClientCertificate is not None or
            self.sslClientKey is not None or
            self.sslServerCertificate is not None
            ):
            return True
        else:
            return False
    def exportLiteral(self, outfile, level, name_='managedSystemType'):
        level += 1
        self.exportLiteralAttributes(outfile, level, name_)
        if self.hasContent_():
            self.exportLiteralChildren(outfile, level, name_)
    def exportLiteralAttributes(self, outfile, level, name_):
        pass
    def exportLiteralChildren(self, outfile, level, name_):
        if self.generatedUUID is not None:
            showIndent(outfile, level)
            outfile.write('generatedUUID=%s,\n' % quote_python(self.generatedUUID).encode(ExternalEncoding))
        if self.localUUID is not None:
            showIndent(outfile, level)
            outfile.write('localUUID=%s,\n' % quote_python(self.localUUID).encode(ExternalEncoding))
        if self.registrationDate is not None:
            showIndent(outfile, level)
            outfile.write('registrationDate=%s,\n' % quote_python(self.registrationDate).encode(ExternalEncoding))
        if self.sslClientCertificate is not None:
            showIndent(outfile, level)
            outfile.write('sslClientCertificate=%s,\n' % quote_python(self.sslClientCertificate).encode(ExternalEncoding))
        if self.sslClientKey is not None:
            showIndent(outfile, level)
            outfile.write('sslClientKey=%s,\n' % quote_python(self.sslClientKey).encode(ExternalEncoding))
        if self.sslServerCertificate is not None:
            showIndent(outfile, level)
            outfile.write('sslServerCertificate=%s,\n' % quote_python(self.sslServerCertificate).encode(ExternalEncoding))
    def build(self, node_):
        attrs = node_.attributes
        self.buildAttributes(attrs)
        for child_ in node_.childNodes:
            nodeName_ = child_.nodeName.split(':')[-1]
            self.buildChildren(child_, nodeName_)
    def buildAttributes(self, attrs):
        pass
    def buildChildren(self, child_, nodeName_):
        if child_.nodeType == Node.ELEMENT_NODE and \
            nodeName_ == 'generatedUUID':
            generatedUUID_ = ''
            for text__content_ in child_.childNodes:
                generatedUUID_ += text__content_.nodeValue
            self.generatedUUID = generatedUUID_
            self.validate_generatedUUID(self.generatedUUID)    # validate type generatedUUID
        elif child_.nodeType == Node.ELEMENT_NODE and \
            nodeName_ == 'localUUID':
            localUUID_ = ''
            for text__content_ in child_.childNodes:
                localUUID_ += text__content_.nodeValue
            self.localUUID = localUUID_
            self.validate_localUUID(self.localUUID)    # validate type localUUID
        elif child_.nodeType == Node.ELEMENT_NODE and \
            nodeName_ == 'registrationDate':
            registrationDate_ = ''
            for text__content_ in child_.childNodes:
                registrationDate_ += text__content_.nodeValue
            self.registrationDate = registrationDate_
        elif child_.nodeType == Node.ELEMENT_NODE and \
            nodeName_ == 'sslClientCertificate':
            sslClientCertificate_ = ''
            for text__content_ in child_.childNodes:
                sslClientCertificate_ += text__content_.nodeValue
            self.sslClientCertificate = sslClientCertificate_
            self.validate_sslClientCertificate(self.sslClientCertificate)    # validate type sslClientCertificate
        elif child_.nodeType == Node.ELEMENT_NODE and \
            nodeName_ == 'sslClientKey':
            sslClientKey_ = ''
            for text__content_ in child_.childNodes:
                sslClientKey_ += text__content_.nodeValue
            self.sslClientKey = sslClientKey_
            self.validate_sslClientKey(self.sslClientKey)    # validate type sslClientKey
        elif child_.nodeType == Node.ELEMENT_NODE and \
            nodeName_ == 'sslServerCertificate':
            sslServerCertificate_ = ''
            for text__content_ in child_.childNodes:
                sslServerCertificate_ += text__content_.nodeValue
            self.sslServerCertificate = sslServerCertificate_
            self.validate_sslServerCertificate(self.sslServerCertificate)    # validate type sslServerCertificate
# end class managedSystemType


class systemInformationType(GeneratedsSuper):
    member_data_items_ = [
        MemberSpec_('systemName', ['string64', 'xsd:token'], 0),
        MemberSpec_('memory', 'xsd:string', 0),
        MemberSpec_('osType', ['string64', 'xsd:token'], 0),
        MemberSpec_('osMajorVersion', ['string64', 'xsd:token'], 0),
        MemberSpec_('osMinorVersion', ['string32', 'xsd:token'], 0),
        MemberSpec_('systemType', ['string32', 'xsd:token'], 0),
        ]
    subclass = None
    superclass = None
    def __init__(self, systemName=None, memory=None, osType=None, osMajorVersion=None, osMinorVersion=None, systemType=None):
        self.systemName = systemName
        self.memory = memory
        self.osType = osType
        self.osMajorVersion = osMajorVersion
        self.osMinorVersion = osMinorVersion
        self.systemType = systemType
    def factory(*args_, **kwargs_):
        if systemInformationType.subclass:
            return systemInformationType.subclass(*args_, **kwargs_)
        else:
            return systemInformationType(*args_, **kwargs_)
    factory = staticmethod(factory)
    def get_systemName(self): return self.systemName
    def set_systemName(self, systemName): self.systemName = systemName
    def validate_systemName(self, value):
        # validate type systemName
        pass
    def get_memory(self): return self.memory
    def set_memory(self, memory): self.memory = memory
    def get_osType(self): return self.osType
    def set_osType(self, osType): self.osType = osType
    def validate_osType(self, value):
        # validate type osType
        pass
    def get_osMajorVersion(self): return self.osMajorVersion
    def set_osMajorVersion(self, osMajorVersion): self.osMajorVersion = osMajorVersion
    def validate_osMajorVersion(self, value):
        # validate type osMajorVersion
        pass
    def get_osMinorVersion(self): return self.osMinorVersion
    def set_osMinorVersion(self, osMinorVersion): self.osMinorVersion = osMinorVersion
    def validate_osMinorVersion(self, value):
        # validate type osMinorVersion
        pass
    def get_systemType(self): return self.systemType
    def set_systemType(self, systemType): self.systemType = systemType
    def validate_systemType(self, value):
        # validate type systemType
        pass
    def export(self, outfile, level, namespace_='inv:', name_='systemInformationType', namespacedef_=''):
        showIndent(outfile, level)
        outfile.write('<%s%s%s' % (namespace_, name_, namespacedef_ and ' ' + namespacedef_ or '', ))
        self.exportAttributes(outfile, level, namespace_, name_='systemInformationType')
        if self.hasContent_():
            outfile.write('>\n')
            self.exportChildren(outfile, level + 1, namespace_, name_)
            showIndent(outfile, level)
            outfile.write('</%s%s>\n' % (namespace_, name_))
        else:
            outfile.write('/>\n')
    def exportAttributes(self, outfile, level, namespace_='inv:', name_='systemInformationType'):
        pass
    def exportChildren(self, outfile, level, namespace_='inv:', name_='systemInformationType'):
        if self.systemName is not None:
            showIndent(outfile, level)
            outfile.write('<%ssystemName>%s</%ssystemName>\n' % (namespace_, self.format_string(quote_xml(self.systemName).encode(ExternalEncoding), input_name='systemName'), namespace_))
        if self.memory is not None:
            showIndent(outfile, level)
            outfile.write('<%smemory>%s</%smemory>\n' % (namespace_, self.format_string(quote_xml(self.memory).encode(ExternalEncoding), input_name='memory'), namespace_))
        if self.osType is not None:
            showIndent(outfile, level)
            outfile.write('<%sosType>%s</%sosType>\n' % (namespace_, self.format_string(quote_xml(self.osType).encode(ExternalEncoding), input_name='osType'), namespace_))
        if self.osMajorVersion is not None:
            showIndent(outfile, level)
            outfile.write('<%sosMajorVersion>%s</%sosMajorVersion>\n' % (namespace_, self.format_string(quote_xml(self.osMajorVersion).encode(ExternalEncoding), input_name='osMajorVersion'), namespace_))
        if self.osMinorVersion is not None:
            showIndent(outfile, level)
            outfile.write('<%sosMinorVersion>%s</%sosMinorVersion>\n' % (namespace_, self.format_string(quote_xml(self.osMinorVersion).encode(ExternalEncoding), input_name='osMinorVersion'), namespace_))
        if self.systemType is not None:
            showIndent(outfile, level)
            outfile.write('<%ssystemType>%s</%ssystemType>\n' % (namespace_, self.format_string(quote_xml(self.systemType).encode(ExternalEncoding), input_name='systemType'), namespace_))
    def hasContent_(self):
        if (
            self.systemName is not None or
            self.memory is not None or
            self.osType is not None or
            self.osMajorVersion is not None or
            self.osMinorVersion is not None or
            self.systemType is not None
            ):
            return True
        else:
            return False
    def exportLiteral(self, outfile, level, name_='systemInformationType'):
        level += 1
        self.exportLiteralAttributes(outfile, level, name_)
        if self.hasContent_():
            self.exportLiteralChildren(outfile, level, name_)
    def exportLiteralAttributes(self, outfile, level, name_):
        pass
    def exportLiteralChildren(self, outfile, level, name_):
        if self.systemName is not None:
            showIndent(outfile, level)
            outfile.write('systemName=%s,\n' % quote_python(self.systemName).encode(ExternalEncoding))
        if self.memory is not None:
            showIndent(outfile, level)
            outfile.write('memory=%s,\n' % quote_python(self.memory).encode(ExternalEncoding))
        if self.osType is not None:
            showIndent(outfile, level)
            outfile.write('osType=%s,\n' % quote_python(self.osType).encode(ExternalEncoding))
        if self.osMajorVersion is not None:
            showIndent(outfile, level)
            outfile.write('osMajorVersion=%s,\n' % quote_python(self.osMajorVersion).encode(ExternalEncoding))
        if self.osMinorVersion is not None:
            showIndent(outfile, level)
            outfile.write('osMinorVersion=%s,\n' % quote_python(self.osMinorVersion).encode(ExternalEncoding))
        if self.systemType is not None:
            showIndent(outfile, level)
            outfile.write('systemType=%s,\n' % quote_python(self.systemType).encode(ExternalEncoding))
    def build(self, node_):
        attrs = node_.attributes
        self.buildAttributes(attrs)
        for child_ in node_.childNodes:
            nodeName_ = child_.nodeName.split(':')[-1]
            self.buildChildren(child_, nodeName_)
    def buildAttributes(self, attrs):
        pass
    def buildChildren(self, child_, nodeName_):
        if child_.nodeType == Node.ELEMENT_NODE and \
            nodeName_ == 'systemName':
            systemName_ = ''
            for text__content_ in child_.childNodes:
                systemName_ += text__content_.nodeValue
            self.systemName = systemName_
            self.validate_systemName(self.systemName)    # validate type systemName
        elif child_.nodeType == Node.ELEMENT_NODE and \
            nodeName_ == 'memory':
            memory_ = ''
            for text__content_ in child_.childNodes:
                memory_ += text__content_.nodeValue
            self.memory = memory_
        elif child_.nodeType == Node.ELEMENT_NODE and \
            nodeName_ == 'osType':
            osType_ = ''
            for text__content_ in child_.childNodes:
                osType_ += text__content_.nodeValue
            self.osType = osType_
            self.validate_osType(self.osType)    # validate type osType
        elif child_.nodeType == Node.ELEMENT_NODE and \
            nodeName_ == 'osMajorVersion':
            osMajorVersion_ = ''
            for text__content_ in child_.childNodes:
                osMajorVersion_ += text__content_.nodeValue
            self.osMajorVersion = osMajorVersion_
            self.validate_osMajorVersion(self.osMajorVersion)    # validate type osMajorVersion
        elif child_.nodeType == Node.ELEMENT_NODE and \
            nodeName_ == 'osMinorVersion':
            osMinorVersion_ = ''
            for text__content_ in child_.childNodes:
                osMinorVersion_ += text__content_.nodeValue
            self.osMinorVersion = osMinorVersion_
            self.validate_osMinorVersion(self.osMinorVersion)    # validate type osMinorVersion
        elif child_.nodeType == Node.ELEMENT_NODE and \
            nodeName_ == 'systemType':
            systemType_ = ''
            for text__content_ in child_.childNodes:
                systemType_ += text__content_.nodeValue
            self.systemType = systemType_
            self.validate_systemType(self.systemType)    # validate type systemType
# end class systemInformationType


USAGE_TEXT = """
Usage: python <Parser>.py [ -s ] <in_xml_file>
"""

def usage():
    print USAGE_TEXT
    sys.exit(1)


def parse(inFileName):
    doc = minidom.parse(inFileName)
    rootNode = doc.documentElement
    rootObj = managedSystemType.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
##     sys.stdout.write('<?xml version="1.0" ?>\n')
##     rootObj.export(sys.stdout, 0, name_="managedSystem", 
##         namespacedef_='')
    return rootObj


def parseString(inString):
    doc = minidom.parseString(inString)
    rootNode = doc.documentElement
    rootObj = managedSystemType.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
##     sys.stdout.write('<?xml version="1.0" ?>\n')
##     rootObj.export(sys.stdout, 0, name_="managedSystem",
##         namespacedef_='')
    return rootObj


def parseLiteral(inFileName):
    doc = minidom.parse(inFileName)
    rootNode = doc.documentElement
    rootObj = managedSystemType.factory()
    rootObj.build(rootNode)
    # Enable Python to collect the space used by the DOM.
    doc = None
##     sys.stdout.write('#from supers_system import *\n\n')
##     sys.stdout.write('import supers_system as model_\n\n')
##     sys.stdout.write('rootObj = model_.managedSystem(\n')
##     rootObj.exportLiteral(sys.stdout, 0, name_="managedSystem")
##     sys.stdout.write(')\n')
    return rootObj


def main():
    args = sys.argv[1:]
    if len(args) == 1:
        parse(args[0])
    else:
        usage()


if __name__ == '__main__':
    #import pdb; pdb.set_trace()
    main()

