#!/bin/sh

# only build what we just tested!
changeset_to_build=$(hg parent -v | grep changeset | cut -c14- | cut -d: -f1)

# run the command 
ssh -o "BatchMode=yes" \
    -o "StrictHostKeyChecking=no" \
    bob@bob01.rdu.rpath.com \
    "(cd build-rba; PATH=\$PATH:\$HOME/bin ./build-rba.sh $changeset_to_build)"
