#!/bin/sh
set -x
function carp_rmake {
    jobid=$1
    nail -s 'Mint Snapshot Build Failed' rbuilder-list@rpath.com << EOT
The rBuilder appliance build failed:

$(rmake q $jobid --logs)
EOT
exit 1
}

/srv/rbuilder/code/mint/scripts/devscripts/rmake-helper --context rba-nightly --commit rbuilder=/products.rpath.com@rpath:rba-devel//rba-nightly >& /tmp/rmake.log
jobid=$?
if [ $jobid != 0 ]; then carp $jobid; fi

exit 0
