#!/bin/sh
set -x
function carp {
    nail -s 'Mint Snapshot Build Failed' tgerla@rpath.com << EOT
The rBuilder appliance build failed:

$(rmake q $? --logs)
EOT
exit
}

/srv/rbuilder/code/mint/scripts/devscripts/rmake-helper --trove rbuilder --context rba-nightly --commit
if [ $? != 0 ]; then carp; fi
