#!/bin/sh
set -x
function carp {
    nail -s 'rBuilder Appliance Build Failed' tgerla@rpath.com << EOT
The rBuilder appliance build failed:

$(tail -n 30 /tmp/create-test-rba.log)
EOT
exit
}

RBATEST=/srv/mint/code/rba/

DATE=$(date +%Y_%m_%d)
MINT_VERSION=$(python -c 'import sys; sys.path.append("/srv/mint/code/mint/"); from mint import constants; print constants.mintVersion')
X86_FLAVOR='~X, ~!alternatives, !bootstrap, ~builddocs,~buildtests, ~desktop, ~dietlibc, ~emacs, ~gcj,~gnome, ~gtk, ~ipv6, ~kde, ~krb, ~ldap, ~nptl,pam, ~pcre, ~perl, ~!pie, ~python, ~qt,~readline, ~!sasl, ~!selinux, ssl, ~tcl,tcpwrappers, ~tk, ~!xen, ~!xfce is: x86(~cmov,~i486, ~i586, ~i686, ~mmx, ~sse, ~sse2)'

cd /srv/mint/code/mint/
make product >& /tmp/create-test-rba.log
if [ $? != 0 ]; then carp; fi

mv mint-$MINT_VERSION.tar.bz2 $RBATEST/mint/mint-$DATE.tar.bz2
sed -ri "s/version\ \=\ '.+'/version\ \=\ \'$DATE\'/" $RBATEST/mint/mint.recipe

pushd $RBATEST/mint/
cvc add mint-$DATE.tar.bz2
cvc cook mint.recipe >& /tmp/create-test-rba.log
if [ $? != 0 ]; then carp; fi

cvc commit --message "automated commit for $DATE snapshot" >& /tmp/create-test-rba.log
if [ $? != 0 ]; then carp; fi

cvc cook mint >& /tmp/create-test-rba.log
if [ $? != 0 ]; then carp; fi

popd
pushd $RBATEST/group-rbuilder-dist/
sed -ri "s/version\ \=\ '.+'/version\ \=\ \'$DATE\'/" group-rbuilder-dist.recipe
cvc merge
cvc commit --message "merge upstream changes"
cvc cook group-rbuilder-dist --flavor "$X86_FLAVOR" >& /tmp/create-test-rba.log
if [ $? != 0 ]; then carp; fi
cvc cook group-rbuilder-dist >& /tmp/create-test-rba.log
if [ $? != 0 ]; then carp; fi

export PYTHONPATH=/srv/mint/code/mint/:/srv/mint/code/conary/
TROVESPEC=$(conary rq group-rbuilder-dist --config "flavor $X86_FLAVOR" --full-versions --flavors)
/srv/mint/code/mint/scripts/create-release rbabeta "$TROVESPEC" installable_iso
TROVESPEC=$(conary rq group-rbuilder-dist --full-versions --flavors)
/srv/mint/code/mint/scripts/create-release rbabeta "$TROVESPEC" installable_iso
