#!/bin/sh
set -x
function carp {
    nail -s 'rBuilder Appliance Build Failed' rbuilder-list@lambchop.rdu.rpath.com << EOT
The rBuilder appliance build failed:

$(tail -n 30 /tmp/create-test-rba.log)
EOT
exit
}

RBATEST=/srv/rbuilder/code/rba/

DATE=$(date +%Y_%m_%d)
X86_FLAVOR='~X, ~!alternatives, !bootstrap, ~builddocs,~buildtests, ~desktop, ~dietlibc, ~emacs, ~gcj,~gnome, ~gtk, ~ipv6, ~kde, ~krb, ~ldap, ~nptl,pam, ~pcre, ~perl, ~!pie, ~python, ~qt,~readline, ~!sasl, ~!selinux, ssl, ~tcl,tcpwrappers, ~tk, ~!xen, ~!xfce is: x86(~cmov,~i486, ~i586, ~i686, ~mmx, ~sse, ~sse2)'

pushd $RBATEST/group-rbuilder-dist/
sed -ri "s/version\ \=\ '.+'/version\ \=\ \'$DATE\'/" group-rbuilder-dist.recipe
cvc merge
cvc commit --message "merge upstream changes"
cvc cook group-rbuilder-dist --flavor "$X86_FLAVOR" >& /tmp/create-test-rba.log
if [ $? != 0 ]; then carp; fi
cvc cook group-rbuilder-dist >& /tmp/create-test-rba.log
if [ $? != 0 ]; then carp; fi

export PYTHONPATH=/srv/rbuilder/code/mint/:/srv/rbuilder/code/conary/
TROVESPEC=$(conary rq group-rbuilder-dist --config "flavor $X86_FLAVOR" --full-versions --flavors)
/srv/rbuilder/code/mint/bin/rbuilder create-product rbabeta "$TROVESPEC" installable_iso
TROVESPEC=$(conary rq group-rbuilder-dist --full-versions --flavors)
/srv/rbuilder/code/mint/bin/rbuilder create-product rbabeta "$TROVESPEC" installable_iso
