#!/bin/sh
set -x
function carp {
    nail -s 'Mint Snapshot Build Failed' tgerla@rpath.com << EOT
The rBuilder appliance build failed:

$(tail -n 30 /tmp/create-test-rba.log)
EOT
exit
}

RBATEST=/srv/rbuilder/code/rba/

DATE=$(date +%Y_%m_%d)
MINT_VERSION=$(python -c 'import sys; sys.path.append("/srv/rbuilder/code/mint/"); from mint import constants; print constants.mintVersion')

cd /srv/rbuilder/code/mint/
make product >& /tmp/create-test-rba.log
if [ $? != 0 ]; then carp; fi

mv mint-$MINT_VERSION.tar.bz2 $RBATEST/mint/mint-$DATE.tar.bz2
sed -ri "s/version\ \=\ '.+'/version\ \=\ \'$DATE\'/" $RBATEST/mint/mint.recipe

pushd $RBATEST/mint/
cvc add mint-$DATE.tar.bz2

cvc commit --message "automated commit for $DATE snapshot" >& /tmp/create-test-rba.log
if [ $? != 0 ]; then carp; fi

popd
