#!/bin/sh
#
# Copyright (C) 2006 rPath, Inc.
# All Rights Reserved
#
# This script generates an rBuilder appliance image from the ground up.
#
# Requirements:
#  * A directory ($RECIPES_PATH) that is set with "cvc context" to
#    point to your nightly branch.
#  * A ~/.rbuilderrc pointing to an rBuilder installation that has
#    your $NIGHTLY_PROJECT specified below.
#  * rBuilder scripts and command line paths specified correctly.
#

RECIPES_PATH=/srv/rbuilder/code/nightly/
NIGHTLY_PROJECT=rbuilder
NIGHTLY_CONTEXT=rba-nightly
NIGHTLY_LABEL=products.rpath.com@rpath:rba-nightly
NIGHTLY_BRANCH=/products.rpath.com@rpath:rba-devel//rba-nightly/
ERROR_MAIL=rbuilder-list@rpath.com

SCRIPTS_PATH=/srv/rbuilder/code/mint/scripts/
CMDLINE_PATH=/srv/rbuilder/code/mint/bin/
KICKSTART_FILE=/home/tgerla/public_html/rba-kickstart.cfg

# source functions library
. $SCRIPTS_PATH/devscripts/nightly-library.sh

# build the image maker image into toolkit-image
merge_and_cook toolkit_inits
merge_and_cook group-image_maker
create_build rbuilder group-image_maker raw_hd_image --wait
merge toolkit-image
fetch_build toolkit-image image_maker.img
commit toolkit-image
cook toolkit-image

# build a new rbuilder snapshot
$SCRIPTS_PATH/devscripts/synchg
create_mint_snapshot
$SCRIPTS_PATH/devscripts/rmake-helper --context=$NIGHTLY_CONTEXT --commit rbuilder=$NIGHTLY_BRANCH
[ $? -ne 0 ] && carp_rmake $?

# build the jobserver root into jobserver-root
merge_and_cook group-jobserver-root
create_build rbuilder group-jobserver-root tarball --wait
merge jobserver-root

get_mint_version
pushd $RECIPES_PATH/jobserver-root
cvc rm *.tgz
fetch_build jobserver-root jobserver-$MINT_VERSION.tgz
cvc add jobserver-$MINT_VERSION.tgz
rewrite_version jobserver-root.recipe $MINT_VERSION
commit jobserver-root
cook jobserver-root
popd

# build a new group-rbuilder-dist
merge group-rbuilder-dist
commit group-rbuilder-dist
# hack to get around our label multiplicity problems
cook group-rbuilder-dist=$NIGHTLY_BRANCH

# trigger ISO and VMware builds from resulting group-rbuilder-dist cook
create_build rbuilder group-rbuilder-dist=$NIGHTLY_BRANCH installable_iso
ISO_ID=$BUILD_ID
create_build rbuilder group-rbuilder-dist=$NIGHTLY_BRANCH vmware_image --wait
VMWARE_ID=$BUILD_ID

# rewrite the kickstart file with the new build id
sed s/@BUILD_ID/$ISO_ID/ $KICKSTART_FILE.in > $KICKSTART_FILE

# somehow trigger a reboot of the kickstarted machine to get a reinstall
# ???

nail -s 'rBuilder Snapshot Build Succeeded' $ERROR_MAIL << EOT
The rBuilder appliance build has finished. New images are available:

$($CMDLINE_PATH/rbuilder build-url $ISO_ID)
$($CMDLINE_PATH/rbuilder build-url $VMWARE_ID)
EOT
