#!/bin/sh
#
# This script removes all traces of any unconfirmed
# users in an rBuilder database so that they can re-register
# or allow an admin to create the account with the username
# they originally requested.
#
from conary import dbstore
from mint import config

cfg = config.MintConfig()
cfg.read(config.RBUILDER_CONFIG)

db = dbstore.connect(cfg.dbPath, cfg.dbDriver)

cu = db.cursor()
cu.execute('SELECT userId, username FROM Users WHERE active=0')

tables = ['UserGroupMembers', 'Users', 'Confirmations']
for userId, username in [(x[0], x[1]) for x in cu.fetchall()]:
    print "Cleaning up %s" % username
    for t in tables:
        cu.execute('DELETE FROM %s WHERE userId=?' % t, userId)
    cu.execute('DELETE FROM UserGroups WHERE userGroup=?', username)
db.commit()
