#!/usr/bin/python
#
# Copyright (c) 2006 rPath, Inc.
#
# All rights reserved
#

import os, sys

from mint import config
from mint.config import RBUILDER_CONFIG
from mint import projects
from conary import dbstore

cfg = config.MintConfig()
cfg.read(RBUILDER_CONFIG)

db = dbstore.connect(cfg.dbPath, driver = cfg.dbDriver)
cu = db.cursor()

cu.execute("SELECT hostname, domainname FROM Projects WHERE external=0")

if cfg.reposDBDriver == 'sqlite':
    repos = projects.SqliteRepositoryDatabase(cfg)
else:
    repos = projects.MySqlRepositoryDatabase(cfg)

dbNames = [x[0] + "." + x[1] for x in cu.fetchall()]
for dbName, count in zip(dbNames, range(len(dbNames))):
    dbName = repos.translate(dbName)
    print "completed %d of %d" % (count, len(dbNames)), chr(13),
    sys.stdout.flush()
    try:
        reposDb = dbstore.connect(cfg.reposDBPath % dbName,
                                  driver = cfg.reposDBDriver)
        cu = reposDb.cursor()

        cu.execute("""UPDATE Permissions SET admin=0 
            WHERE userGroupId IN 
            (SELECT userGroupId 
                FROM UserGroups 
                WHERE userGroup != 'mintauth')""")
        reposDb.commit()

        cu.execute("SELECT * from Users WHERE userName='anonymous'")
        if not cu.fetchone():
            print "database %s has no anonymous user" % dbName
    except:
        e = sys.exc_info()[1]
        if str(e).startswith('Unknown database'):
            continue
        if str(e) == 'unable to open database file':
            continue
        print "error in database: %s\n %s" % (dbName, str(e))

print 79 * ' ', chr(13),
print "Migration complete"
