#!/bin/env python2.4

from conary.lib import util

from rmake.cmdline import helper
from rmake.build import buildtrove

import optparse
import os
import sys
import time

sys.excepthook = util.genExcepthook()

parser = optparse.OptionParser()
parser.add_option("-c", "--context",
    action="store", type="string", dest="context")
parser.add_option("--commit", action = "store_true",
    default = False, dest = "commit")

(options, args) = parser.parse_args()

if len(args) == 0:
    print "No troves specified"
    sys.exit(-1)

rm = helper.rMakeHelper(context = options.context)

jobId = rm.buildTroves(args)
job = rm.client.getJob(jobId)
while not job.isFinished():
    time.sleep(2)
    job = rm.client.getJob(jobId)

if job.isBuilt():
    print "Trove built successfully"
    if options.commit:
        rm.commitJob(jobId)
    sys.exit(0)
else:
    print "Trove cook failed!"
    sys.exit(-1)
