#!/bin/sh

SYNCDIRS="/srv/rbuilder/code/mint /srv/rbuilder/code/conary /srv/www/html/web/"

# disable temporarily by touching /tmp/.nosynchg
if [ -f /tmp/.nosynchg ]; then
   exit 0
fi

# sync
for d in $SYNCDIRS; do
    (cd $i; hg pull && hg update)
done

# restart web server
sudo killall -USR1 httpd
