#!/bin/sh

# disable temporarily by touching /tmp/.nosynchg
if [ -f /tmp/.nosynchg ]; then
   exit 0
fi

# save dir
pushd .

# sync mint
cd /srv/mint/code/mint
hg pull
hg update

cd /srv/mint/code/conary
hg pull
hg update

cd /srv/www/html/web/
hg pull
hg update

# restore dir
popd

# restart web server
sudo killall -USR1 httpd
