#!/bin/sh

SYNCDIRS="/srv/rbuilder/code/mint /srv/rbuilder/code/conary /srv/www/html/web/ /srv/rbuilder/code/rmake"

# disable temporarily by touching /tmp/.nosynchg
if [ -f /tmp/.nosynchg ]; then
   exit 0
fi

# sync
for i in $SYNCDIRS; do
    (cd $i; hg pull && hg update)
done

pushd /srv/rbuilder/code/mint
PYTHONPATH=/srv/rbuilder/code/mint:/srv/rbuilder/code/conary:/srv/rbuilder/code/rmake make clean all
popd

# restart web server
sudo killall -USR1 httpd
