#
# Copyright (c) 2005-2007 rPath, Inc.
#
# All rights reserved
#

python_files = __init__.py outboundmirror.py

all: default-all

install: raaplugins-install default-install

clean: default-clean


include ../../../../Make.rules
