#!/usr/bin/python2.4
#
# Copyright (c) 2004-2005 rpath, Inc.
#
import conary
import sys
import os

if os.environ.has_key("CONARY_PATH"):
    sys.path.insert(0, os.environ['CONARY_PATH'])
else:
    sys.path.insert(0, "/usr/share/conary/")

sys.path.insert(0, ".")

import sqlite3
from imagetool import users

def addUser(dbPath, username):
    db = sqlite3.connect(dbPath, timeout = 30000)

    usersTable = users.UsersTable(db, None)
    return usersTable.newUser(username, True)

def usage():
    print "usage: %s <username> <path to imagetool db>" % sys.argv[0]
    sys.exit(1)

if len(sys.argv) != 3:
    usage()

uid = addUser(sys.argv[2], sys.argv[1])
print "User added. Id: %d" % uid
