#!/bin/sh -x
#
# Copyright (c) 2004-2005 rPath, Inc.
# All rights reserved
#

conary=conary

scriptdir=/usr/lib/anaconda-runtime/           # directory to run anaconda scripts from
arch=i386                   # architecture of the distro
topdir=/srv/rbuilder/templates/$arch/          # top directory of the CD image
subdir=rPath                # directory under $topdir that contains base/
distroname="rPath Linux"    # name of the distro
distroversion=0.50          # version of the distro

while [ $# -ge 1 ]; do
    case $1 in
	--scriptdir) scriptdir="$2"; shift; shift;;
	--topdir) topdir="$2"; shift; shift;;
	--name) distroname="$2"; shift; shift;;
	--version) distroversion="$2"; shift; shift;;
	--arch) arch="$2"; shift; shift;;
	--subdir) subdir="$2"; shift; shift;;
	--install-label) 
	    installlabel=$2;
	    conaryargs="$conaryargs --install-label $2"; 
	    shift; shift
	    ;;
	*) echo "unknown option $1";;
    esac
done

mkdir -p $topdir/$subdir/changesets/

conary --install-label $installlabel changeset kernel[!kernel.smp] $topdir/$subdir/changesets/kernel-2.6-$arch.ccs
conary --install-label $installlabel changeset kernel[kernel.smp] $topdir/$subdir/changesets/kernel-smp-2.6-$arch.ccs

# Internal variables: No need to modify these
# temporary directory where anaconda is extracted
if [ "x$scriptdir" == "x" ]; then
# extract anaconda scripts
    anacondadir=$(mktemp -d /tmp/bd-anaconda-XXXXXX)
    $conary $conaryargs --root $anacondadir update anaconda --no-deps
    # the location of anaconda's scripts
    scriptdir=$anacondadir/usr/lib/anaconda-runtime
fi

# instroot staging directories
instroot=$(mktemp -d /tmp/bd-instroot-XXXXXX)
instrootgr=$(mktemp -d /tmp/bd-instrootgr-XXXXXX)

# build the images
sh -x $scriptdir/upd-instroot --conary --install-label "$installlabel" --arch "$arch" $topdir/$subdir/changesets $instroot $instrootgr
sh -x $scriptdir/mk-images --conary $topdir/$subdir/changesets $topdir $instroot $instrootgr $arch "$distroname" $distroversion $subdir

$scriptdir/makestamp.py --releasestr="$distroname" --arch="$arch" --discNum="1" --baseDir=$subdir/base --packagesDir=$subdir/changesets --pixmapsDir=$subdir/pixmaps --outfile=$topdir/.discinfo

rm -rf $anacondadir $instroot $instrootgr
rm -f $topdir/$subdir/changesets/*.ccs
chmod 0664 $topdir/isolinux/isolinux.*

mv $topdir/$subdir $topdir/BUILDNAME
