#!/usr/bin/python

from conary import dbstore
from conary.lib import util
import os
import struct
import sys

def checkFiles(reposPath, dbDriver, dbPath):
    db = dbstore.connect(dbPath, dbDriver)
    contentsPath = os.path.join(reposPath, 'contents')

    cu = db.cursor()
    cu.execute("SELECT COUNT(sha1) FROM FileStreams")
    l = int(cu.fetchone()[0])

    print "Reading %d streams from repository..." % l
    cu.execute('select distinct sha1 from filestreams')
    missing = []

    i = 0

    x = cu.fetchmany(1000)
    # postgres' implementation of fetchmany returns an array with the number
    # of items requested.  If fewer than the number of items requested is 
    # returned from the database, it is padded with Nones
    while x and x[0] != None:
        for r in x:
            if not r:
                break
            i += 1
            if r[0]:
                sha = ''.join(('%02x' % ord(j) for j in r[0]))
            else:
                continue
            splitSha = struct.unpack('2s2s36s', sha)
            if not os.path.exists(os.path.join(contentsPath, *splitSha)):
                missing.append(sha)

            if i % 500:
                print '\rprogress: %d/%d%s' % (i, l, '\b' * 50),
        x = cu.fetchmany(1000)


    print "\nNot all file streams will need to be checked. %d streams not checked." % (l-i)

    db.close()
    return missing

if __name__ == '__main__':
    if len(sys.argv) < 4:
        print "Usage: %s <path-to-repository> <db-driver> <db-path>" % sys.argv[0]
        sys.exit(1)

    r = checkFiles(sys.argv[1], sys.argv[2], sys.argv[3])

    if r:
        print "Missing contents:", r
    else:
        print "No missing contents found."
