#!/usr/bin/python

from conary import dbstore
from conary.lib import util
import os
import struct
import sys

def checkFiles(reposPath):
    db = dbstore.connect(os.path.join(reposPath, 'sqldb'), 'sqlite')
    contentsPath = os.path.join(reposPath, 'contents')

    cu = db.cursor()
    cu.execute("SELECT COUNT(sha1) FROM FileStreams")
    l = int(cu.fetchone()[0])

    print "Reading %d streams from repository..." % l
    cu.execute('select distinct hex(sha1) from filestreams')
    missing = []

    i = 0

    x = cu.fetchmany(1000)
    while x:
        for r in x:
            i += 1
            sha = r[0]
            if not sha:
                continue
            splitSha = struct.unpack('2s2s36s', sha)
            if not os.path.exists(os.path.join(contentsPath, *splitSha)):
                missing.append(sha)

            if i % 500:
                print '\rprogress: %d/%d%s' % (i, l, '\b' * 50),
        x = cu.fetchmany(1000)


    print "\nNot all file streams will need to be checked. %d streams not checked." % (l-i)

    db.close()
    return missing

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print "Usage: %s <path-to-repository>" % sys.argv[0]
        sys.exit(1)

    r = checkFiles(sys.argv[1])

    if r:
        print "Missing contents:", r
    else:
        print "No missing contents found."
