#!/usr/bin/python
import os
import sys

maybeRoot = os.path.dirname(os.path.dirname(__file__))
if os.path.exists(os.path.join(maybeRoot, 'mint', 'lib')):
    sys.path.insert(0, maybeRoot)

from mint.scripts import createplatforms
sys.exit(createplatforms.Script().run())
