#!/usr/bin/python
import logging
from conary import conarycfg
from mint.lib.siteauth import SiteAuthorization
logging.getLogger().addHandler(logging.StreamHandler())
cfg = conarycfg.ConaryConfiguration(True)
auth = SiteAuthorization('/srv/rbuilder/data/authorization.cfg', cfg)
if auth.isConfigured():
    print 'Already configured; keeping existing blob.'
else:
    print 'Generating ...'
    auth.generate()

print 'rBuilder ID:', auth.rBuilderId
print 'Entitlement key:', auth.entitlementKey
