#!/bin/sh
#
# Copyright (c) 2008 rPath, Inc.
# All rights reserved.
#
# This script is executed from the group after each update. It migrates
# the mint database and all repository databases.
#
# NOTE: In the interests of avoiding cruft which no-one can explain 3
# years from now, all transitional migrations, workarounds, and anything
# that will not otherwise be self-explanatory in the future should be
# marked with a comment indicating when and for what version it was
# added as well as any relevant issue IDs.

if [[ `awk '{print $2}' /proc/mounts | grep -c ^/proc$` > 1 ]]
then
    # If /proc appears to be mounted more than once, then it means we're
    # chrooted. It manifests itself this way as the actual path is
    # outside the chroot and thus can't be addressed.
    is_chrooted=1
fi

check_apache() {
    pidof httpd > /dev/null 2>&1
}

shutdown_apache() {
    if check_apache; then
        service httpd stop
        for i in $(seq 30); do
            if check_apache; then
                sleep 1
            else
                break
            fi
        done
        if check_apache; then
            echo "WARNING: httpd still running, killing httpd"
            killall httpd > /dev/null 2>&1
            if check_apache; then
                echo "WARNING: httpd *still* running, sending httpd signal 9"
                killall -9 httpd > /dev/null 2>&1
                if check_apache; then
                    echo "WARNING: failed to shutdown the Apache (httpd) service"
                fi
            fi
        fi
    fi
}

die() {
    echo "ERROR:" "$@"
    exit 1
}

# Shut down apache, if it's running
shutdown_apache

# Restart postgresql since it does not like the rPL 1 -> rPL 2
# migration and probably does not like being run post-update either.
#   -- 5.0.0 - 2009-01-08
function waitForPg()
{
  echo "Waiting for postgres startup to complete"
  ready="false"
  retries=4
  while [ "$ready" == "false" ]
  do
    psql -U postgres -p 5439 -l >/dev/null 2>&1
    rc=$?
    if [ "$rc" -eq 0 ]
    then
      ready="true"
    elif [[ "$rc" -eq 2 && "$retries" -ne 0 ]]
    then
      retries=$(( $retries - 1 ))
      sleep 4
    else
      echo "Failed waiting for Postgres"
      exit 1
    fi
  done
}

service postgresql-rbuilder condstop
service postgresql-rbuilder start
waitForPg

# Migrate the mint database (or create it if it doesn't exist)
/usr/share/rbuilder/scripts/rbuilder-database --migrate \
    || die "Failed to migrate the rBuilder database"
chown apache:apache /srv/rbuilder/data/{db,platformName.cache}

# Migrate all conary repositories
/usr/share/rbuilder/scripts/migrate-all-projects || die "Failed to migrate all repositories"

# Migrate the mint config
/usr/share/rbuilder/scripts/migrate-config --migrate || die "Failed to migrate the rBuilder configuration file"
chown apache:apache /srv/rbuilder/config/rbuilder-generated.conf
# raa-web user needs to be in apache group so that rbuilder-generated is readable by rapa
usermod -a -G apache raa-web

# Create a project for rMake to use as a repository.
sudo -u apache /usr/share/rbuilder/scripts/rmake-setup

# Set up external repositories for the platforms we support
# this can't be run as apache as it needs root access to read the
# entitlement dir
/usr/share/rbuilder/scripts/init-extproducts

# Start apache, if not chrooted
if [ "x$is_chrooted" == "x" ]
then
    service httpd start
fi

### Extra Steps

# Re-add postgresql initscripts so that it picks up a new chkconfig.d entry
#   -- pre-4.1.0 - 2008-05-16
for initscript in postgresql postgresql-rbuilder
do
    if [ -f /etc/init.d/$initscript ]
    then
        /sbin/chkconfig --del $initscript
        /sbin/chkconfig --add $initscript
    fi
done


# Generate rMake certificates IFF we're not chrooted; otherwise we
# might end up sticking them pre-generated in the ISOs which would be
# very bad.
#   -- 5.0.0 - 2008-12-01
if [ "x$is_chrooted" == "x" ]
then
    /usr/share/rbuilder/scripts/generate-certs.sh \
        || die "Failed to generate certificates"
else
    echo Skipping certificate generation due to chrooting
fi

# Restart rMake after update + cert generation.
if [ -f /var/lock/subsys/rmake ]
then
    service rmake restart
    service rmake-node restart
fi

# Shut down postgres if chrooted
if [ "x$is_chrooted" == "x1" ]
then
    service postgresql-rbuilder stop
fi


exit 0
