#!/usr/bin/python
#
# Copyright (c) 2005-2007 rPath, Inc.
#
# All Rights Reserved
#

import os
import sys
import re

from mint import config

from conary import dbstore

JOBSERVER_DIR = '/srv/rbuilder/jobserver'
JOBSERVER_LOG = 'srv/rbuilder/logs/job-server.log'
MINT_LOG = 'srv/mint/logs/job-server.log'
PS = '/bin/ps -p'
KILL = '/bin/kill'


def clearJobData(jobId):
    cfg = config.MintConfig()
    cfg.read(config.RBUILDER_CONFIG)
    db = dbstore.connect(cfg.dbPath, cfg.dbDriver)
    cu = db.cursor()
    cu.execute("""UPDATE Jobs SET status = 4, 
                  statusMessage = 'Job failed to complete' WHERE jobId=?""", 
                  jobId)
    db.commit()

def findPid(jobId):
    jsdirs = [x for x in os.listdir(JOBSERVER_DIR) if os.path.isdir(os.path.join(JOBSERVER_DIR, x))]    
    for x in jsdirs:
        try:
            fd = open(os.path.join(JOBSERVER_DIR, x, JOBSERVER_LOG))
        except IOError:
            try:
                fd = open(os.path.join(JOBSERVER_DIR, x, MINT_LOG))
            except IOError:
                sys.exit(1)

        match = re.compile('\[(\d+)\] INFO:.*job.*started.*\(id %s\)' % jobId)
        for y in fd:
            p = match.search(y)
            if p:
                pid = p.group(1)
                if not os.system('%s %s 1>& /dev/null' % (PS, pid)):
                     return pid
        fd.close()
    return None

def main(jobid):
    pid = findPid(jobid)
    if not pid:
        clearJobData(jobid)
        sys.exit(1)
    if os.system('%s %s' % (KILL, pid)):
        if os.system('%s -9 %s' % (KILL, pid)):
            sys.exit(1)
        clearJobData(jobid)

if __name__ == '__main__':
    main(sys.argv[1])
