#!/usr/bin/python
from mint import config
from mint.scripts import loadmirror
from mint.lib import scriptlibrary

import os, sys
import logging

cfg = config.MintConfig()
cfg.read(config.RBUILDER_CONFIG)

log = scriptlibrary.getScriptLogger()

if os.getuid():
    log.error("You must run this script as root.")
    sys.exit(1)

scriptlibrary.setupScriptLogger(consoleLevel = logging.INFO,
    logfile = os.path.join(cfg.logPath, 'load-mirror.log'))

source = "/mnt/mirror/"
statusFile = os.path.join(cfg.dataPath, 'run', 'load-status.txt')

loader = loadmirror.LoadMirror(source,
    'http://%s:%s@localhost/xmlrpc-private/' % (cfg.authUser, cfg.authPass))

loadmirror.mountMirrorLoadDrive()

for serverName in os.listdir(source):
    if not os.path.exists(os.path.join(source, serverName, "MIRROR-INFO")):
        continue
    log.info("processing %s", serverName)

    numFiles = loader.parseMirrorInfo(serverName)
    cb = loadmirror.Callback(serverName, numFiles, statusFile = statusFile)

    try:
        project = loader.findTargetProject(serverName)
    except RuntimeError, e:
        log.warning(e)
    except Exception, e:
        log.error(e)
        raise
    else:
        log.info("Found project eligible to load: %s", serverName)
        loader.copyFiles(serverName, project, callback = cb.callback)
