#!/bin/bash
#
# mcp-stack:  Starts the rBuilder MCP stack
#
# chkconfig: - 24 15
# description: Controls the entire MCP stack
# processname: mcp
# config: /usr/bin

#
# Copyright (c) 2007 rPath, Inc.
#
# All rights reserved
#

start() {
    rm -f /var/lib/stompserver/*
    /sbin/service stompserver start
    /sbin/service mcp start
    /sbin/service jobmaster start
}

stop() {
    /sbin/service jobmaster stop
    /sbin/service mcp stop
    /sbin/service stompserver stop
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop 
        start
        ;;
  *)
    echo "Usage: `basename $0` {start|stop|restart}"
    ;;
esac
