#!/bin/bash
#
# Copyright (c) SAS Institute Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# chkconfig: - 24 15
# description: Controls the entire MCP stack
# processname: mcp
# config: /usr/bin

start() {
    /sbin/service mcp-dispatcher start
    /sbin/service jobmaster start
    /sbin/service gunicorn reload
}

stop() {
    /sbin/service jobmaster stop
    /sbin/service mcp-dispatcher stop
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop 
        start
        ;;
  *)
    echo "Usage: `basename $0` {start|stop|restart}"
    ;;
esac
