#!/usr/bin/python
#
# Copyright 2006 rPath, Inc.
# All Rights Reserved
#
from mint import config

import shutil
import sys
import os

backupFile = "/srv/rbuilder/rbuilder.conf-pre-2.0.3"

# check for a vital setting in /srv/rbuilder/config/rbuilder-generated.conf
f = open("/srv/rbuilder/config/rbuilder-generated.conf")
genConfig = f.read()
if 'hostName' in genConfig:
    print "migrate-config has already been run (/srv/rbuilder/config/rbuilder-generated.conf already contains a hostName entry)"
    sys.exit(1)
f.close()

shutil.copy("/srv/rbuilder/rbuilder.conf", backupFile)

oldCfg = config.MintConfig()
oldCfg.read("/srv/rbuilder/rbuilder.conf")

newCfg = config.MintConfig()
newCfg.read("/srv/rbuilder/config/rbuilder.conf")

if not newCfg.configured:
    print "migate-config will not run on instance of rbuilder which has not been configured"
    sys.exit(1)

allKeys = set(oldCfg.keys())
generatedKeys = set(config.keysForGeneratedConfig)
customKeys = allKeys - generatedKeys

# save "generated" keys to rbuilder-generated.conf
generatedFile = open("/srv/rbuilder/config/rbuilder-generated.conf", "w")
for k in generatedKeys:
    oldCfg.displayKey(k, out = generatedFile)
generatedFile.close()

# everything else that is different from the stock config goes
# in rbuilder-custom.conf
customFile = open("/srv/rbuilder/config/rbuilder-custom.conf", "w+")
for k in customKeys:
    if k == "visibleBuildTypes":
        continue
    if newCfg[k] != oldCfg[k]:
        oldCfg.displayKey(k, out = customFile)
customFile.close()

# patch the old config file to indicate that it's not being used anymore
f = open("/srv/rbuilder/rbuilder.conf", "w")
print >> f, """# THIS FILE IS NO LONGER USED, IT REMAINS AS A PLACEHOLDER.
# Any modifications made here will not take effect. Please see:
#
#   /srv/rbuilder/config/rbuilder-custom.conf
#
# ...to make modifications to rBuilder's configuration."""
f.close()

sys.exit(0)
