#!/usr/bin/python
#
# Copyright (c) 2006 rPath, Inc.
#
# All rights reserved
#

import os, sys

from mint import config, RBUILDER_CONFIG
from mint import maintenance
from conary import dbstore
from conary.server import schema

cfg = config.MintConfig()
cfg.read(RBUILDER_CONFIG)

if maintenance.getMaintenanceMode(cfg)==maintenance.NORMAL_MODE:
    print >> sys.stderr, "rBuilder repositories are not locked. rBuilder"
    print >> sys.stderr, "administrators can place the site in this mode."
    sys.exit(1)

db = dbstore.connect(cfg.dbPath, driver = cfg.dbDriver)
cu = db.cursor()

cu.execute("SELECT hostname, domainname FROM Projects")

if cfg.reposDBDriver == 'sqlite':
    dbNames = [x[0] + "." + x[1] for x in cu.fetchall()]
else:
    dbNames = [x[0] + "_" + x[1].replace('.', '_') for x in cu.fetchall()]

for dbName, count in zip(dbNames, range(len(dbNames))):
    print "completed %d of %d" % (count, len(dbNames)), chr(13),
    sys.stdout.flush()
    try:
        reposDb = dbstore.connect(cfg.reposDBPath % dbName,
                                  driver = cfg.reposDBDriver)
        schema.loadSchema(reposDb)
    except:
        e = sys.exc_info()[1]
        if str(e).startswith('Unknown database'):
            continue
        if str(e) == 'unable to open database file':
            continue
        print "error in database: %s\n %s" % (dbName, str(e))

print 79 * ' ', chr(13),
print "Migration complete"
