#!/bin/sh
INSTROOTS_DIR=/srv/imagetool/instroots
ARCH=x86
LABEL=conary.rpath.com@rpl:devel

instroot_dir=$INSTROOTS_DIR/$ARCH/instroot
instrootgr_dir=$INSTROOTS_DIR/$ARCH/instrootgr
anaconda_dir=$INSTROOTS_DIR/$ARCH/anaconda

mkdir -p $instroot_dir
mkdir -p $instrootgr_dir
mkdir -p $anaconda_dir
mkdir -p $INSTROOTS_DIR/csdir/

conary update --root $anaconda_dir anaconda=$LABEL[is:$ARCH] --no-deps

sh -x $anaconda_dir/usr/lib/anaconda-runtime/upd-instroot --debug --conary --arch %ARCH %INSTROOTS_DIR/csdir/ $instroot_dir $instrootgr_dir
