#!/bin/bash
#
# Copyright (c) SAS Institute Inc.
#

scriptdir=$(dirname $0)

. /etc/sysconfig/pgsql/postgresql-rbuilder
export PGDATA PGPORT

"$scriptdir"/postgres-auto-update || exit 1

# mint database
createuser -SdRU postgres rbuilder &>/dev/null
createdb -U postgres --encoding=UTF8 --owner=rbuilder mint &>/dev/null
"$scriptdir"/rbuilder-database --migrate || exit 1

# jabberd database
createuser -SDRU postgres jabberd &>/dev/null
createdb -U postgres --encoding=UTF8 --owner=jabberd jabberd &>/dev/null && \
    psql -U jabberd -d jabberd -Xqf /usr/share/rbuilder/jabberd/db-setup.pgsql

# rMake 3 database
createuser -SDRU postgres rmake &>/dev/null
createdb -U postgres --encoding=UTF8 --owner=rmake rmake &>/dev/null

# rMake 2 database
createdb -U postgres --encoding=UTF8 --owner=rmake rmake2 &>/dev/null

# SSL certificates
"$scriptdir"/generate-certs.sh


rand_passwd() {
    xxd -ps -l16 /dev/urandom
}

# Configure the local rmake node's identity and add it to the dispatcher's
# whitelist.
ident=/srv/rmake3/worker.ident
if [ ! -f $ident ]
then
  domain=rbuilder.rpath
  username=$(rand_passwd)
  password=$(rand_passwd)
  echo "xmppPermit ${username}@${domain}" >> /etc/rmake3/server.d/21_whitelist.conf

  ident_tmp=$(mktemp --tmpdir=$(dirname $ident))
  echo "rbuilder.rpath ${username} ${password}" >> $ident_tmp
  mv $ident_tmp $ident
fi

# Internal password
auth_file=/srv/rbuilder/config/config.d/01_authpass.conf
if [ ! -f $auth_file ]
then
    conf_tmp=$(mktemp --tmpdir=$(dirname $auth_file))
    echo authPass $(rand_passwd) >$conf_tmp
    mv $conf_tmp $auth_file
fi


exit 0
