#!/usr/bin/python
#
# Copyright (c) 2010 rPath, Inc.
#
# All Rights Reserved
#
"""
This script can be used to check for and handle current system inventory events
"""

import sys
from mint.scripts import process_system_events

if __name__ == '__main__':
    sys.exit(process_system_events.ProcessSystemEvents().run())
    
