#!/usr/bin/python
from mcp import client
import sys

old_stdout = sys.stdout
sys.stdout = open('/dev/null', 'w')

cfg = client.MCPClientConfig()
try:
    cfg.queueHost = sys.argv[1]
except IndexError:
    pass # default to localhost

c = client.MCPClient(cfg)

queue_length = 0
for x in c.jobStatus().itervalues():
    if x['status'][0] < 300:
        queue_length += 1

print >>old_stdout, queue_length

c.disconnect()
