#!/bin/bash
#
# Copyright (c) SAS Institute Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


if [ $# -ne 1 -o  \( "$1" != enable -a "$1" != disable \) ]; then
    echo "Usage: $0 <enable|disable>"
    exit 1
fi

if [ "$1" == enable ]; then
    install -d -m 0700 -o apache -g apache /tmp/rbuilder_debug_logging
    touch /srv/rbuilder/MINT_LOGGING_ENABLE
else
    rm -f /srv/rbuilder/MINT_LOGGING_ENABLE
fi
