#!/bin/sh
#
# A simple script to reset a bunch of stuff for repository testing. 
#

CONARY_PATH=/usr/lib/python2.4/site-packages/

MINT_DATA=/srv/mint
AUTH_REPO=/srv/authrepo

rm -rf $MINT_DATA/repos/
rm $MINT_DATA/data/db
rm -rf $AUTH_REPO/repo/

mkdir -p $MINT_DATA/repos $MINT_DATA/contents $MINT_DATA/data/ $MINT_DATA/tmp/
mkdir -p $AUTH_REPO/repo/

touch $MINT_DATA/data/db
echo mintpass | $CONARY_PATH/conary/server/server.py --add-user mintauth $AUTH_REPO/repo/

chown -R $USERNAME.apache $MINT_DATA/data/ $MINT_DATA/repos/ $MINT_DATA/contents $MINT_DATA/tmp/ $AUTH_REPO
chmod -R ug+rw            $MINT_DATA/data/ $MINT_DATA/repos/ $MINT_DATA/contents $MINT_DATA/tmp/ $AUTH_REPO

#mailman lists
if [ -f /var/mailman/bin/list_lists ]; then
    for list in `/var/mailman/bin/list_lists | grep -viE 'found|mailman' | awk '{print $1}'`; do
        /var/mailman/bin/rmlist -a $list > /dev/null
    done
    #fix the permissions on the aliases files
    chown mailman:mailman /var/mailman/data/aliases*
fi
