#!/usr/bin/python
import logging
import os
import pwd
import sys
from mint.db import database
from mint.db import repository
from mint.lib import scriptlibrary
from mint.rest.db import database as restdb

log = logging.getLogger(__name__)


class Script(scriptlibrary.GenericScript):
    logFileName = 'scripts.log'
    newLogger = True

    def action(self):
        self.loadConfig()
        self.resetLogging(verbose=True)
        fqdn, dump = sys.argv[1:]

        if os.getuid() == 0:
            pwnam = pwd.getpwnam('apache')
            os.setgid(pwnam.pw_gid)
            os.setuid(pwnam.pw_uid)
            log.info("Dropped privilieges to uid %d", pwnam.pw_uid)

        db = database.Database(self.cfg)
        mgr = repository.RepositoryManager(self.cfg, db)
        handle = mgr.getRepositoryFromFQDN(fqdn)
        handle.restoreBundle(dump, replaceExisting=True)

        restDb = restdb.Database(self.cfg, db)
        restDb.productMgr.reposMgr.populateUsers(handle)
        restDb.platformMgr.platformCache.clear()

        mgr.close()
        db.close()


sys.exit(Script().run())
