#!/bin/bash -e
#
# Copyright (c) SAS Institute Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


cd `dirname $0`
if [ $EUID -ne 0 ]; then
    echo This script must be run as root.
    exit 1
fi
. /etc/sysconfig/pgsql/postgresql-rbuilder
export PGDATA PGPORT
superopt="--user=postgres"
pgbopt="--no-psqlrc --quiet --user=pgbouncer --port=6432"

[ -f /var/lock/subsys/rmake-node ] && /sbin/service rmake-node stop
[ -f /var/lock/subsys/rmake ] && /sbin/service rmake stop

# "service rmake reset" doesn't clean up postgres yet
psql $pgbopt -Xc 'kill rmake2'
dropdb $superopt rmake2 ||:
createdb $superopt --encoding=UTF8 --owner=rmake rmake2
psql $pgbopt -Xc 'resume rmake2'

./deleteproject --force rmake-repository \
    || echo "Warning: failed to delete project rmake-repository"
/usr/sbin/rmake-server reset \
    || echo "Warning: failed to delete rMake database"
# Creates repository and repository user, and restarts rmake and rmake-node
puppet apply /usr/share/rbuilder/scripts/rmake-setup.pp

exit 0
