#!/usr/bin/python
#
# Copyright (c) 2005-2007 rPath, Inc.
#
# All rights reserved
#

from mint import config
from mint import mint_error
from mint import scriptlibrary
from mint import rmake_setup
import traceback
import sys

class CreateRmakeProject(scriptlibrary.SingletonScript):
    cfgPath = config.RBUILDER_CONFIG
    rmakeCfgPath = config.RBUILDER_RMAKE_CONFIG

    def action(self):
        cfg = config.getConfig(self.cfgPath)
        if cfg.configured:
            try:
                rmake_setup.setupRmake(cfg, self.rmakeCfgPath)
            except mint_error.RmakeRepositoryExistsError:
                # Not an error condition, but provide a useful return code
                return 1
        else:
            print ('warning: not initializing rMake repository as '
                    'initial setup has not been run')
        return 0

if __name__ == "__main__":
    create = CreateRmakeProject()
    sys.exit(create.run())
