#!/bin/bash -e
cd `dirname $0`
if [ $EUID -ne 0 ]; then
    echo This script must be run as root.
    exit 1
fi
. /etc/sysconfig/pgsql/postgresql-rbuilder
export PGDATA PGPORT
superopt="--user=postgres"
pgbopt="--no-psqlrc --quiet --user=pgbouncer --port=6432"

[ -f /var/lock/subsys/rmake-node ] && /sbin/service rmake-node stop
[ -f /var/lock/subsys/rmake ] && /sbin/service rmake stop

# "service rmake reset" doesn't clean up postgres yet
psql $pgbopt -Xc 'kill rmake2'
dropdb $superopt rmake2 ||:
createdb $superopt --encoding=UTF8 --owner=rmake rmake2
psql $pgbopt -Xc 'resume rmake2'

./deleteproject --force rmake-repository \
    || echo "Warning: failed to delete project rmake-repository"
/usr/sbin/rmake-server reset \
    || echo "Warning: failed to delete rMake database"
# Creates repository and repository user, and restarts rmake and rmake-node
puppet apply /usr/share/rbuilder/scripts/rmake-setup.pp

exit 0
