#!/bin/bash -e
cd `dirname $0`
if [ $EUID -ne 0 ]; then
    echo This script must be run as root.
    exit 1
fi
. /etc/sysconfig/pgsql/postgresql-rbuilder
export PGDATA PGPORT

if [ -f /var/lock/subsys/rmake-node ]; then /sbin/service rmake-node stop; fi
if [ -f /var/lock/subsys/rmake ]; then /sbin/service rmake stop; fi

# "service rmake reset" doesn't clean up postgres yet
dropdb -U postgres rmake2 &>/dev/null ||:
createdb -U postgres --encoding=UTF8 --owner=rmake rmake2

./deleteproject --force rmake-repository \
    || echo "Warning: failed to delete project rmake-repository"
/sbin/service rmake reset --force \
    || echo "Warning: failed to delete rMake database"
sudo -u apache ./rmake-setup

/sbin/service rmake start
/sbin/service rmake-node start
/sbin/service httpd reload
