#!/usr/bin/python
#
# Copyright (c) 2010 rPath, Inc.
#
# All Rights Reserved
#
"""
This script can be used to import running systems from predefined targets
"""

import sys
from mint.scripts import target_systems_import

if __name__ == '__main__':
    sys.exit(target_systems_import.TargetSystemsImport().run())
    
