#!/usr/bin/python
#
# update-package-index-external
#
# Updates the package index for external projects on rBuilder
# using a net repository client.
#
# Copyright (c) 2005-2007 rPath, Inc.
#
# All rights reserved
#

from mint.scripts import pkgindexer
import os

if __name__ == "__main__":
    import sys, time, random
    if '--cron' in sys.argv:
        # spread out the load on the upstream repository
        # by sleeping somewhere between 0 and 30 minutes
        time.sleep(random.randrange(0, 3000) * .6)
        sys.argv.remove('--cron')
    upie = pkgindexer.UpdatePackageIndexExternal()
    os._exit(upie.run())

