#!/usr/bin/python
#
# Copyright (c) 2005-2006 rPath, Inc.
#
# All rights reserved
#
from mint import pkgindex
import os

if __name__ == "__main__":
    upi = pkgindex.UpdatePackageIndex()
    os._exit(upi.run())
