#!/usr/bin/python
#
# Copyright (c) 2005-2007 rPath, Inc.
#
# All rights reserved
#
from mint import pkgindexer
import os

if __name__ == "__main__":
    upi = pkgindexer.UpdatePackageIndex()
    os._exit(upi.run())
