#!/usr/bin/python

from conary import conarycfg
import sys
from mint.config import MintConfig, RBUILDER_CONFIG
from mint.lib.siteauth import SiteAuthorization

try:
    proxyCfg = sys.argv[1]
    mintCfg = MintConfig()
    mintCfg.read(RBUILDER_CONFIG)
    ccfg = conarycfg.ConaryConfiguration(True)
    ccfg.read(proxyCfg)
    siteauth = SiteAuthorization(mintCfg.siteAuthCfgPath, conaryCfg=ccfg)
    siteauth.getApi()
except Exception, e:
    print >> sys.stderr, e
    sys.exit(1)
sys.exit(0)
