#
# Copyright (c) 2008 rPath, Inc.
#
# All rights reserved
#

python_files = \
	__init__.py		\
	rmakemanagement.py


all: default-all

install: raaplugins-install default-install

clean: default-clean

include ../../../../Make.rules
