#!/bin/bash -x
# A quick script to setup an image
mount -n -t proc /proc /proc
mount -n -t sysfs /sys /sys

#/bin/dmesg -n level
state=`LC_ALL=C awk '/ \/ / && ($3 !~ /rootfs/) { print $4 }' /proc/mounts`
[ "$state" != "rw" -a "$READONLY" != "yes" ] && mount -n -o remount,rw /

#Make the uml devices
mknod /dev/ubda b 98 0
mknod /dev/udba1 b 98 1

# Clear mtab
(> /etc/mtab) &> /dev/null

# Enter mounted filesystems into /etc/mtab
mount -f /
mount -f /proc >/dev/null 2>&1
mount -f /sys >/dev/null 2>&1
mount -f /dev/pts >/dev/null 2>&1

[ -f /tmp/pre-tag-scripts ] && /bin/sh /tmp/pre-tag-scripts

#Script generated by conary update --tag-script
[ -f /tmp/tag-scripts ] && /bin/sh /tmp/tag-scripts

[ -f /tmp/post-tag-scripts ] && /bin/sh /tmp/post-tag-scripts

#Script generated by conary update --tag-script
[ -f /tmp/kernel-tag-scripts ] && /bin/sh /tmp/kernel-tag-scripts

[ -f /tmp/post-kernel-tag-scripts ] && /bin/sh /tmp/post-kernel-tag-scripts

bash

#clean up the udb devices
rm /dev/udba1
rm /dev/udba

rm -rf /tmp/*
umount /proc
umount /sys
umount /dev/pts

mount -n -o remount,ro /

bash

/sbin/halt -f -p
