#!/bin/sh
SERVER_PATH=@SERVER_PATH@
export PGDATA=$SERVER_PATH/postgresql
export PGPORT=5439
PGENGINE=/usr/bin
PGLOG=$SERVER_PATH/postgresql.log

killall postmaster

if [ -f $PGDATA/PG_VERSION ] && [ -d $PGDATA/base ] 
    then
    echo "oo";
else
# no existing version
    echo -n $"Initializing database: ";
    if [ ! -e $PGDATA -a ! -h $PGDATA ]
    then
            mkdir -p $PGDATA || exit 1
    fi
    $PGENGINE/initdb --pgdata=$PGDATA >> $PGLOG 2>&1 < /dev/null
    [ ! -f $PGDATA/PG_VERSION ] && exit 1
fi
$SERVER_PATH/scripts/startpostmaster.py
sleep 2
pid=`pidof -s $PGENGINE/postmaster`
if [ $pid ] && [ -f "${PGDATA}/postmaster.pid" ]
then
   echo "Started"
else
   echo "Failed"
   exit 1
fi
createlang -p ${PGPORT} plpgsql template1 >> $PGLOG 2>&1
