#
# Copyright (c) 2005 rpath, Inc.
#
# All Rights Reserved
#

dist_files = Makefile httpd.conf.in ssl.conf.in test.crt test.key

all: default-all

dist: default-dist

clean: default-clean

include ../../Make.rules
# vim: set sts=8 sw=8 noexpandtab :
