#
# Copyright (c) 2005-2007 rPath, Inc.
#
# All rights reserved
#

SUBDIRS = static

python_files = __init__.py outboundmirror.py

all: default-all

install: all raaplugins-install default-install

clean: default-clean


include ../../../../Make.rules
